### ISSUE TITLE
AttributeError: 'MolTreeNode' object has no attribute 'cid'

### ISSUE THREAD

**Issue by lihan1997** [wengong-jin/icml18-jtnn#35] opened 2019-03-03 11:59 UTC
Hi!
This error occurs when I ran sample.py in fast_molvae without any changes.

Traceback (most recent call last):
  File "/fast_molvae/sample.py", line 39, in <module>
    print model.sample_prior()
  File "/jtnn_vae.py", line 119, in sample_prior
    return self.decode(z_tree, z_mol, prob_decode)
  File "/fast_jtnn/jtnn_vae.py", line 200, in decode
    jtenc_holder, mess_dict = JTNNEncoder.tensorize_nodes(pred_nodes, scope)
  File "/fast_jtnn/jtnn_enc.py", line 73, in tensorize_nodes
    cid = y.cid[1] if y.cid[0] == x.idx else 0
AttributeError: 'MolTreeNode' object has no attribute 'cid'

Process finished with exit code 1

Maybe something wrong with your codes?

Thank you!

**Comment by wengong-jin** [comment] 2019-03-04 04:44
Hi,

The issue is fixed. I accidentally committed some codes that are still developing :)

My apologies

**Closed by wengong-jin** 2019-03-04 04:44 UTC

**Comment by lihan1997** [comment] 2019-03-04 08:27
Thanks！
